version: '3.9'
services:
  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - database
    env_file:
      - backend/.env
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@database:3306/database
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - frontend/.env
    ports:
      - 5173:5173