services:
  database:
    image: mysql:8.0
    container_name: database
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - database
    env_file:
      - backend/.env
    environment:
      - DATABASE_URL=${DB_URL}
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - frontend/.env
    ports:
      - 5173:5173