# Generated by Django 5.2.7 on 2025-10-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_list_public_token'),
        ('tasks', '0002_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lists.list', verbose_name='Task lists'),
        ),
    ]
