# Generated by Django 5.2.7 on 2025-10-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_task_category_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
    ]
