# Generated by Django 5.2.7 on 2025-10-28 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be hex format (#RRGGBB).', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
