# Generated by Django 5.2.7 on 2025-10-28 14:47

import lists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='public_token',
            field=models.CharField(default=lists.models.generate_public_token, editable=False, max_length=30, unique=True),
        ),
    ]
