# Generated by Django 5.2.7 on 2025-10-28 20:15

import lists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='public_token',
            field=models.CharField(db_index=True, default=lists.models.generate_public_token, editable=False, max_length=30, unique=True),
        ),
    ]
